CREATE OR REPLACE DATABASE IF NOT EXISTS ANALYTICS;
CREATE OR REPLACE SCHEMA IF NOT EXISTS ANALYTICS.LMC;

CREATE OR REPLACE TABLE ANALYTICS.LMC.LMC_RAW_DATA (
    SHIPMENT_DATE VARCHAR,
    BARCODE VARCHAR,
    ACCOUNT_NUMBER VARCHAR,
    INVOICE_NUMBER VARCHAR,
    CONSIGNMENT VARCHAR,
    REFERENCE VARCHAR,
    WEIGHT NUMBER(18, 4),
    VOLUMETRIC_WEIGHT NUMBER(18, 4),
    LENGTH NUMBER(10, 0),
    WIDTH NUMBER(10, 0),
    HEIGHT NUMBER(10, 0),
    PRODUCT_TYPE_NAME VARCHAR,
    DESTINATION VARCHAR,
    ZONE VARCHAR,
    BASE_RATE NUMBER(18, 4),
    FINAL_PRICE NUMBER(18, 4),
    LOAD_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP
);
